services:
  oracle-db:
    image: gvenzl/oracle-xe
    container_name: oracle-db
    environment:
      - ORACLE_PASSWORD=azizmarco23
      - APP_USER=system
      - APP_USER_PASSWORD=azizmarco23
    ports:
      - "15215:1521"
    networks:
      - mynet

  mybank-app:
    image: mybank-image
    container_name: mybank-app
    depends_on:
      - oracle-db
    ports:
      - "8085:8080"
    networks:
      - mynet

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - mynet

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - mynet

  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    ports:
      - "9100:9100"
    networks:
      - mynet

networks:
  mynet:
    driver: bridge
