package com.mybank.model;

public enum FolderNavigation {
    CREE_PAR_CHARGE,             // CREATED_BY_OFFICER
    ENVOYE_AU_DIRECTEUR,         // SENT_TO_DIRECTOR
    EN_COURS_D_ETUDE_DIRECTEUR,  // UNDER_REVIEW_BY_DIRECTOR
    RETOURNE_AU_CHARGE,          // RETURNED_TO_OFFICER
    REENVOYE_AU_DIRECTEUR,       // RESUBMITTED_TO_DIRECTOR
    APPROUVE_PAR_DIRECTEUR,      // APPROVED_BY_DIRECTOR
    REJETE_PAR_DIRECTEUR,        // REJECTED_BY_DIRECTEUR
    TERMINE,                     // COMPLETED
    ASSIGNE_A_ANALYSTE,
    RETOURNE_DE_Analyste,
    ENVOYE_AU_RESPONSABLE_ANALYSTE,
    RETOUR_OFFRE,
    APPROUVE_PAR_ENGAGEMENT,      
    REJETE_PAR_ENGAGEMENT,
    ENVOYE_AU_DIRECTEUR_ENGAGEMENT,
    ENVOYE_AU_SUCCURSALE,
    ASSIGNE_A_ANALYSTECIC,
    ENVOYE_AU_DIRECTEUR_CIC,
    RETOURNE_DE_AnalysteCIC,
    APPROUVE_PAR_CIC,      
    REJETE_PAR_CIC,
    		
}

